version: "3"
services:
  # Postgres
  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    networks:
      - some-net

  # Server
  server:
    container_name: server
    restart: unless-stopped
    build: .
    entrypoint: /app/server-entrypoint.sh
    ports: 
      - "8000:8000"
    volumes:
      - static_volume:/app/agtools/static
    command: python manage.py runserver 0.0.0.0:8000 --pdb
    links:
      - db
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_DB=postgresql
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_NAME=mydb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PYTHONUNBUFFERED=1
    networks:
      - some-net

networks:
  some-net:
    name: custom_network
    driver: bridge
volumes:
    static_volume: {}
    postgres_data: {}